Voordelen: 'Advantages'
Voor wie: 'Voor wie'
Home: 'Home'
home.banner.title: 'The practical hospitality software'
home.banner.subtitle: 'Easily manage all your orders and control food costs with SeeYouResto – the solution for your restaurant.'
Ontdek de voordelen: 'Discover the advantages'
home.about.title: 'About Us'
home.about.subtitle: 'Our software is born from years of experience in the hospitality industry, providing a perfectly tailored solution.'
home.about.description: 'With deep industry knowledge, we developed SeeYouResto to address the unique challenges of the hospitality sector. Our mission is to make your operations more efficient and profitable.'
home.about.advantages.0.title: 'Experienced'
home.about.advantages.0.description: 'Built by hospitality experts for you.'
home.about.advantages.1.title: 'Effective'
home.about.advantages.1.description: 'Increase your efficiency immediately.'
home.what-we-do.title: 'Our solutions'
home.what-we-do.subtitle: 'Efficient ordering and accurate food cost calculation.'
read-more: 'Read more'
home.cta-banner.title: 'Discover the power of SeeYouResto'
home.cta-banner.subtitle: 'Transform your hospitality business today.'
home.cta-banner.button: 'Request a free quote now'
Navigeer: 'Navigate'
Wettelijk: 'Legal'
Privacybeleid: 'Privacy Policy'
Cookiebeleid: 'Cookie Policy'
Cookie instellingen: 'Cookie Settings'
Onze oplossingen: 'Our solutions'
