Voordelen: 'Avantages'
Voor wie: 'Pour qui'
Home: 'Accueil'
home.banner.title: "Le logiciel pratique pour l'hôtellerie"
home.banner.subtitle: 'Gérez facilement toutes vos commandes et contrôlez les coûts alimentaires avec SeeYouResto – la solution pour votre restaurant.'
Ontdek de voordelen: 'Découvrez les avantages'
home.about.title: 'À propos de nous'
home.about.subtitle: "Notre logiciel est né de nombreuses années d'expérience dans l'hôtellerie, offrant une solution parfaitement adaptée."
home.about.description: "'Avec une connaissance approfondie du secteur, nous avons développé SeeYouResto pour répondre aux défis uniques de l'hôtellerie. Notre mission est de rendre vos opérations plus efficaces et rentables.'"
home.about.advantages.0.title: 'Expérimenté'
home.about.advantages.0.description: 'Construit par des experts en hôtellerie pour vous.'
home.about.advantages.1.title: 'Efficace'
home.about.advantages.1.description: 'Augmentez immédiatement votre efficacité.'
home.what-we-do.title: 'Nos solutions'
home.what-we-do.subtitle: 'Commandes efficaces et calcul précis des coûts alimentaires.'
read-more: 'En savoir plus'
home.cta-banner.title: 'Découvrez la puissance de SeeYouResto'
home.cta-banner.subtitle: "Transformez votre entreprise hôtelière dès aujourd'hui."
home.cta-banner.button: 'Demandez un devis gratuit maintenant'
Navigeer: 'Naviguer'
Wettelijk: 'Légal'
Privacybeleid: 'Politique de confidentialité'
Cookiebeleid: 'Politique de cookies'
Cookie instellingen: 'Paramètres des cookies'
Onze oplossingen: 'Nos solutions'
